---
channel: stable
addons:
  steve:
    repository: erik73/addon-steve
    target: steve
    image: ghcr.io/erik73/steve/{arch}
  mailserver:
    repository: erik73/addon-mail
    target: mail
    image: ghcr.io/erik73/mailserver/{arch}
  mailfilter:
    repository: erik73/addon-mailfilter
    target: mailfilter
    image: ghcr.io/erik73/mailfilter/{arch}
  tellsticklive:
    repository: erik73/addon-tellsticklive
    target: tellsticklive
    image: ghcr.io/erik73/tellsticklive/{arch}
  mariadb:
    repository: erik73/addon-mariadb
    target: mariadb
    image: ghcr.io/erik73/mariadb/{arch}
  phpmyadmin:
    repository: erik73/addon-phpmyadmin
    target: phpmyadmin
    image: ghcr.io/erik73/phpmyadmin/{arch}
  mailserver2:
    repository: erik73/addon-mail2
    target: mail2
    image: ghcr.io/erik73/mailserver2/{arch}
