name: Mailfilter
version: 3.0.4
slug: mailfilter
description: Rspamd mailfilter for Home Assistant
url: https://github.com/erik73/hassio-addons
arch:
- aarch64
- amd64
- armv7
stage: experimental
init: false
ingress: true
panel_icon: mdi:filter
hassio_api: true
ingress_port: 1337
map:
- ssl:rw
options:
  enable_antivirus: false
  enable_dkim_signing: false
schema:
  enable_antivirus: bool
  enable_dkim_signing: bool
image: ghcr.io/erik73/mailfilter/{arch}
