name: MariaDB
slug: mariadb
version: 1.0.2
description: A SQL database server
url: https://github.com/erik73/hassio-addons
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
backup_post: unlock-tables-for-backup
backup_pre: lock-tables-for-backup
image: ghcr.io/erik73/mariadb/{arch}
init: false
options:
  databases:
  - homeassistant
  logins:
  - password: null
    username: homeassistant
  rights:
  - database: homeassistant
    username: homeassistant
ports:
  3306/tcp: null
schema:
  databases:
  - str
  logins:
  - username: str
    password: password
  rights:
  - database: str
    privileges:
    - list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|CREATE VIEW|DELETE|DELETE
      HISTORY|DROP|EVENT|GRANT OPTION|INDEX|INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?
    username: str
  mariadb_server_args:
  - str?
services:
- mysql:provide
startup: system
timeout: 300
