---
name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material
          mkdir -p docs
          curl https://raw.githubusercontent.com/erik73/repository-beta/master/README.md --output docs/beta.md
          curl https://raw.githubusercontent.com/erik73/repository-edge/master/README.md --output docs/edge.md
          ln -sf ../README.md docs/index.md
          ln -sf ../LICENSE.md docs/license.md
          ln -sf ../CONTRIBUTING.md docs/contributing.md
          ln -sf ../CODE_OF_CONDUCT.md docs/code-of-conduct.md


      - run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: erik73/erik73.github.io
          publish_branch: master
          publish_dir: ./site
